x=set(["Apple","Mango"])
y=set(["Mango","Orange"])
z=set(["Mango"])
print("First set:",x)
print("Second set:",y)
print("Third set:",z)
print("X is subset of Y?",x.issubset(y))
print("Z is subset of X?",z.issubset(x))
print("Intersection of X and Y:",x.intersection(y))
print("Union of X and Y:",x.union(y))